export enum NavIcon {
  REPORTS = 'summarize',
  PRODUCTS = 'inventory_2',
  DELIVERY_RECEIPT = 'local_shipping',
  PURCHASE_ORDER = 'fact_check',
  SOA = 'article',
  TRANSACTIONS = 'account_balance',
  VOUCHERS = 'newspaper',
  CUSTOMERS = 'group',
  WAREHOUSES = 'warehouses',
  SUPPLIERS = 'conveyor_belt',
  USERS = 'person',
  SETTINGS = 'settings',
  ROLES = 'badge',
  STOCK_CHECKER = 'checklist_rtl',
}
